# Generated by Django 5.2.7 on 2025-10-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='posts/video_posters/', verbose_name='Превью видео'),
        ),
    ]
